### ISSUE TITLE
Gradle plugin is using a deprecated feature to be removed in Gradle 6.0

### ISSUE THREAD

**Issue by swpalmer** [spotbugs/spotbugs-gradle-plugin#105]
Internal API constructor TaskReportContainer(Class<T>, Task) has been deprecated. This is scheduled to be removed in Gradle 6.0.
        at org.gradle.api.reporting.internal.TaskReportContainer.<init>(TaskReportContainer.java:32)
        at com.github.spotbugs.internal.SpotBugsReportsImpl.<init>(SpotBugsReportsImpl.java:15)
        at com.github.spotbugs.internal.SpotBugsReportsImpl_Decorated.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:155)
        at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:329)
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:47)
        at com.github.spotbugs.SpotBugsTask.<init>(SpotBugsTask.java:91)
        at com.github.spotbugs.SpotBugsTask_Decorated.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by ati90ati** [comment]
Hey, this cannot be fixed earlier than the 2.0.0 version?

**Comment by KengoTODA** [comment]
Yes. I think major version up is the best timing to break backward compatibility.

What is your concern? Is Gradle v6 coming soon?

**Comment by ati90ati** [comment]
Gradle 6 is not yet here.
I try to avoid to have warnings and to use deprecated code.

2.0.0 is ok for me, however 1.7.0 sounds much better.
Do you have an idea when you will succeed to release 2.0.0?
 

Problem 2:
Also in the version 1.6.10 in an application with Spring Boot I get these errors:

> Task :spotbugsMain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
The following classes needed for analysis were missing:
  call
  get
  makeConcatWithConstants
  apply
  accept
  test

**Comment by ati90ati** [comment]
NOTE: in the plugin version 1.6.9 it did not appear, but unfortunately in the 1.6.10 / 1.6.11 / 1.7.0  yes.

I've created a sample project:
https://github.com/ati90ati/bugreport-spotbugs-gradle-plugin-logging
