### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory in Gradle 5.1,5.6.2,etc.

### ISSUE THREAD

**Issue by TysonAndre** [spotbugs/spotbugs-gradle-plugin#157]
I'm using a plugin for spotbugs that uses commons-digester, which uses commons-logging, and that plugin crashes during initialization because the commons-logging library was excluded.

I believe that the cause is this section of code ` configuration.exclude(excludeProperties("commons-logging", "commons-logging")); `:

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/459a117c20526342dd2636454bb7e8fe17ea97ce/src/main/java/com/github/spotbugs/SpotBugsPlugin.java#L169-L176

spotbugs assumes that commons-logging will always be provided by the gradle runtime, but that seems not to be the case in the latest gradle versions. (testing with 5.1, 5.6.1). I've tried various approaches to forcibly include commons-logging, but nothing seems to work (e.g.  explicitly adding `        spotbugs 'commons-logging:commons-logging:1.2'` next to other dependencies)

```
Caused by: java.lang.RuntimeException: Could not instantiate com.example.ExampleDetector as Detector
        at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector(DetectorFactory.java:85)
        at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector2(DetectorFactory.java:103)
        at edu.umd.cs.findbugs.DetectorFactory.createDetector2(DetectorFactory.java:397)
        at edu.umd.cs.findbugs.plan.AnalysisPass.instantiateDetector2sInPass(AnalysisPass.java:132)
        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:992)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
        at com.github.spotbugs.internal.spotbugs.SpotBugsExecutor.runSpotbugs(SpotBugsExecutor.java:23)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:118)
        at org.gradle.process.internal.worker.request.WorkerAction.runThenStop(WorkerAction.java:101)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector(DetectorFactory.java:79)
        ... 16 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
        at org.apache.commons.digester3.Digester.<init>(Digester.java:282)
```

**Comment by TysonAndre** [comment]
The plugin in question works properly (and I see issues from that plugin in build/reports/spotbugs/main.xml) if I take out the line excluding commons-logging, and build spotbugs-gradle-plugin locally (and install to local repo) with https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories

I didn't find any documentation on how to build this plugin locally in the docs, so I'm mentioning the steps I use if I need to revisit this:

```
// local changes to build.gradle of the project using spotbugs-gradle-plugin
buildscript {
    // https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories
    repositories {
        /*maven {
            // has internal url
        }*/
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.github.spotbugs:spotbugs-gradle-plugin:2.0.1-SNAPSHOT'
    }
}
apply plugin: 'com.github.spotbugs'


// local changes to settings.gradle
pluginManagement {
    repositories {
        /*maven {
            // has internal url
        }*/
        mavenLocal()
        gradlePluginPortal()
    }
}

```

```patch
--- a/src/main/java/com/github/spotbugs/SpotBugsPlugin.java
+++ b/src/main/java/com/github/spotbugs/SpotBugsPlugin.java
@@ -172,7 +172,6 @@ public class SpotBugsPlugin extends AbstractCodeQualityPlugin<SpotBugsTask> {
         configuration.exclude(excludeProperties("org.apache.ant", "ant-launcher"));
         configuration.exclude(excludeProperties("org.slf4j", "jcl-over-slf4j"));
         configuration.exclude(excludeProperties("org.slf4j", "log4j-over-slf4j"));
-        configuration.exclude(excludeProperties("commons-logging", "commons-logging"));
         configuration.exclude(excludeProperties("log4j", "log4j"));
         configureConfiguration(configuration);
```

**Comment by TysonAndre** [comment]
I ended up switching from commons-digester to jackson-xml for xml unserializing for different reasons, so this is no longer an issue for me.

This can be closed, unless you think this would affect more potential use cases.

**Comment by KengoTODA** [comment]
For future reference: Please refer #180 and try the new implementation, it should work, but supports Gradle 5.6+ only.
