### ISSUE TITLE
Could not generate HTML output in 4.0.5

### ISSUE THREAD

**Issue by DanySK** [spotbugs/spotbugs-gradle-plugin#228]
Configuration:

```kotlin
spotbugs {
    ignoreFailures.set(true)
    setEffort("max")
    setReportLevel("low")
    showProgress.set(true)
    val excludeFile = File("${project.rootProject.projectDir}/config/spotbugs/excludes.xml")
    if (excludeFile.exists()) {
        excludeFilter.set(excludeFile)
    }
}

tasks.withType<SpotBugsTask> {
    reports {
        create("html") {
            enabled = true
        }
    }
}
```

Project has errors.

Result of `./gradlew check`

```
> Task :spotbugsMain
Scanning archives (3 / 3)
2 analysis passes to perform
Pass 1: Analyzing classes (131 / 131) - 100% complete
Pass 2: Analyzing classes (3 / 3) - 100% complete
Done with analysis
Warning at xsl:variable on line 348 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
Warning at xsl:variable on line 351 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
Type error evaluating ((./Class)/@classname) in xsl:sort/@select on line 285 column 41 of default.xsl:
  XTTE1020: A sequence of more than one item is not allowed as the @select attribute of
  xsl:sort (@classname="org.kaikikm.threadresloader.ResourceLoader",
  @classname="org.kaikikm.threadresloader.AccessibleURLClassLoader") 
at template generateWarningTable on line 275 of default.xsl:
     invoked by xsl:call-template at file:///home/danysk/.gradle/workers/default.xsl#203
     invoked by unknown caller (class net.sf.saxon.expr.instruct.ForEach) at file:///home/danysk/.gradle/workers/default.xsl#198
  In template rule with match="/" on line 69 of default.xsl
The following errors occurred during analysis:
  Could not generate HTML output
    net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the @select attribute of xsl:sort (@classname="org.kaikikm.threadresloader.ResourceLoader", @classname="org.kaikikm.threadresloader.AccessibleURLClassLoader") 
      At net.sf.saxon.expr.Expression.typeError(Expression.java:1464)
      At net.sf.saxon.expr.SingletonAtomizer.evaluateItem(SingletonAtomizer.java:221)
      At net.sf.saxon.expr.SingletonAtomizer.evaluateItem(SingletonAtomizer.java:31)
      At net.sf.saxon.expr.sort.SortExpression.evaluateSortKey(SortExpression.java:394)
      At net.sf.saxon.expr.sort.SortedIterator.buildArray(SortedIterator.java:215)
      At net.sf.saxon.expr.sort.SortedIterator.doSort(SortedIterator.java:231)
      At net.sf.saxon.expr.sort.SortedIterator.next(SortedIterator.java:148)
      At net.sf.saxon.om.FocusTrackingIterator.next(FocusTrackingIterator.java:73)
      At net.sf.saxon.trans.Mode.applyTemplates(Mode.java:455)
      At net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:300)
      At net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:255)
      At net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
      At net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132)
      At net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352)
      At net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299)
      At net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
      At net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:243)
      At net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353)
      At net.sf.saxon.expr.LetExpression.process(LetExpression.java:608)
      At net.sf.saxon.expr.instruct.ForEach.lambda$processLeavingTail$0(ForEach.java:484)
      At net.sf.saxon.om.SequenceIterator.forEachOrFail(SequenceIterator.java:128)
      At net.sf.saxon.expr.instruct.ForEach.processLeavingTail(ForEach.java:484)
      At net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
      At net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132)
      At net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352)
      At net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299)
      At net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:721)
      At net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
      At net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132)
      At net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352)
      At net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299)
      At net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:352)
      At net.sf.saxon.trans.Mode.applyTemplates(Mode.java:532)
      At net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:747)
      At net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
      At net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
      At net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
      At edu.umd.cs.findbugs.HTMLBugReporter.finish(HTMLBugReporter.java:73)
      At edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
      At edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1165)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
      At com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:91)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
      At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:47)
      At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:41)
      At org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
      At org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:41)
      At org.gradle.workers.internal.IsolatedClassloaderWorker.execute(IsolatedClassloaderWorker.java:49)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:84)
      At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.base/java.lang.reflect.Method.invoke(Method.java:566)
      At org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:129)
      At org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:126)
      At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.base/java.lang.reflect.Method.invoke(Method.java:566)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
      At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
      At java.base/java.lang.Thread.run(Thread.java:834)

SpotBugs reported failures
org.gradle.api.GradleException: Verification failed: SpotBugs violation found: 5
        at com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:97)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:47)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:41)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:41)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.execute(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:129)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:126)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

An HTML report is generated but the content is incomplete. In particular, the file/line details of each violation are not there.

**Comment by iloveeclipse** [comment]
You need fixed xsl file from https://github.com/spotbugs/spotbugs/pull/1112

**Comment by DanySK** [comment]
Is this going to get pulled automatically by the Gradle plugin?

**Comment by DanySK** [comment]
Sorry, the previous comment was probably unclear. I meant to ask if, and when in case, the change in the xsl file it's going to get delivered with spotbugs, and in turn used by default by this plugin.

**Comment by vorburger** [comment]
#235 comments may be useful for how to generate HTML reports?

**Comment by jscancella** [comment]
@DanySK are you still having this issue with the latest version of the spotbugs plugin?

**Comment by DanySK** [comment]
Seems to be [working in 4.2.3](https://travis-ci.org/github/AlchemistSimulator/Alchemist/jobs/691946267).
