### ISSUE TITLE
ReportsDir is always null

### ISSUE THREAD

**Issue by Charis1331** [spotbugs/spotbugs-gradle-plugin#255]
In an Android multi-module project, I get the following every time I run the SpotBugs task.
```
org.gradle.api.GradleException: Verification failed: SpotBugs violation found: 1. SpotBugs report can be found in null
        at com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:104)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:42)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:42)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:136)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:133)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
```
My `spotbugs.gradle` file:
```
spotbugs {
    toolVersion = '4.0.2'
}

task spotbugs(type: SpotBugsTask) {
    group = 'verification'
    description "Generate spotbugs reports"
    ignoreFailures = ignoreFailuresGlobalFlag /* whether to allow the build to continue if there are warnings */
    effort = "min" /* analysis effort level. Possible values : min, default, or max */
    reportLevel = "medium" /* priority threshold for reporting bugs -> low, medium, or high */
    excludeFilter = new File("$configDir/spotbugs/spotbugs-filter.xml")
    classes = files("$project.buildDir/intermediates/javac")
}
```

I tried to set the `reportsDir` manually, but it doesn't work. I am running _SpotBugsBase plugin_ **v4.2.0** with the _Gradle_ **v6.4**.

**Comment by davidburstromspotify** [comment]
Are you applying `com.github.spotbugs-base` or `com.github.spotbugs`? If the former, I believe you need to add

```
reports {
   html.enabled true
}
```

in the configuration block. Otherwise the `getFirstEnabledReport` will return null.

**Comment by Charis1331** [comment]
> Are you applying `com.github.spotbugs-base` or `com.github.spotbugs`? If the former, I believe you need to add
> 
> ```
> reports {
>    html.enabled true
> }
> ```
> 
> in the configuration block. Otherwise the `getFirstEnabledReport` will return null.

 As I mentioned in my post, I am using the Base plugin. Also, the reports block is not available in the latest versions.

**Comment by davidburstromspotify** [comment]
> Also, the reports block is not available in the latest versions.

It is, but on the SpotBugsTask instance where it configures the `NamedDomainObjectContainer` called `reports`. I.e.

```
task spotbugs(type: SpotBugsTask) {
    ...
    reports {
        html.enabled true
    }
}
```

**Comment by Charis1331** [comment]
> > Also, the reports block is not available in the latest versions.
> 
> It is, but on the SpotBugsTask instance where it configures the `NamedDomainObjectContainer` called `reports`. I.e.
> 
> ```
> task spotbugs(type: SpotBugsTask) {
>     ...
>     reports {
>         html.enabled true
>     }
> }
> ```
Well It was the first thing I tried (coming from v3.x) but I got an error that the xml (I guess the same goes for html) is not recognised. Are you using the latest version of the plugin and you are still able to configure that, not to mention get a valid reports' directory?

**Comment by davidburstromspotify** [comment]
I also use the latest versions and the base plugin, but I had to drop the `xml` configuration from the block. I also do the configuration in `project.afterEvaluate` but I'm not sure if that has any effect. I get HTML reports then (although not with the custom XSLT applied, but that's a separate issue).

**Comment by Charis1331** [comment]
@KengoTODA Again, this was **not** solved but instead covered by not displaying the message 

> "SpotBugs report can be found in null".
The remaining issue that the reportsDir is null no matter what, still exists in the **latest** _base gradle plugin_.

**Comment by jscancella** [comment]
@Charis1331 can you post your full build file so I can try to reproduce?

**Comment by Charis1331** [comment]
Hi @jscancella,
Sorry for the very late reply. This is the code in my `spotbugs.gradle` file:
```
task spotbugs(type: SpotBugsTask) {
    group = 'verification'
    description "Generate spotbugs reports"
    ignoreFailures = ignoreFailuresGlobalFlag /* whether to allow the build to continue if there are warnings */
    effort = "min" /* analysis effort level. Possible values : min, default, or max */
    reportLevel = "medium" /* priority threshold for reporting bugs -> low, medium, or high */
    excludeFilter = new File("$configDir/spotbugs/spotbugs-filter.xml")
    classes = files("$project.buildDir/intermediates/javac")
}
```
which I configure in my **root** `build.gradle` file:
```
[...]
subprojects {
    apply plugin: "com.github.spotbugs-base"
    //noinspection UnnecessaryQualifiedReference
    project.extensions.extraProperties.set('SpotBugsTask', com.github.spotbugs.snom.SpotBugsTask)
    apply from: "$project.rootDir/config/quality.gradle"

}
```
I always get the same error, no matter what I've tried:
```
org.gradle.api.GradleException: 4 SpotBugs violations were found.
        at com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:115)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:42)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:42)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:136)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:133)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by jscancella** [comment]
@Charis1331 that still isn't a full project so I am unable to test. However, I noticed you are applying `com.github.spotbugs-base`. That is not the way to use this plugin - please see https://plugins.gradle.org/plugin/com.github.spotbugs. If you are still having issues after correctly applying the plugin please open a new issue.
