### ISSUE TITLE
Spotbug 4.1.1 issue with dom4j2.1.3

### ISSUE THREAD

**Issue by saradach** [spotbugs/spotbugs-gradle-plugin#370]
Gradle version 6.5
dom4j2.1.3 when I down grade to 2.1.1. it works fine

## spotbug configuration

```
dependencies {
        classpath("org.springframework.boo:spring-boot-gradle-plugin:4.5.1")
}

apply plugin: 'com.github.spotbugs'

spotbugs {
    reportLevel = 'high'
    toolVersion = '4.1.4'
}
spotbugsMain {
    reports {
        xml.enabled = false
        html {
            enabled = true
            stylesheet = 'fancy-hist.xsl'
        }
    }
}
```

## Error

```
edu.umd.cs.findbugs.PluginException: Couldn't parse "jar:file:/C:/Users/xx/.gradle/caches/modules-2/files-2.1/com.github.spotbugs/spotbugs/4.1.1/6d29f411f3e0e90f5ef07a8c1a6d791b8e
1e84d9/spotbugs-4.1.1.jar!/messages.xml"
        at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1288)
        at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
        at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
         at edu.umd.cs.findbugs.DetectorFactoryCollection.<clinit>(DetectorFactoryCollection.java:57)
    com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:90)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.dom4j.DocumentException
        at org.dom4j.io.SAXReader.read(SAXReader.java:513)
        at org.dom4j.io.SAXReader.read(SAXReader.java:408)
        at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1285)
        ... 38 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.gjt.xpp.impl.tokenizer.Tokenizer.next(Tokenizer.java:1274)
        at org.gjt.xpp.impl.pullparser.PullParser.next(PullParser.java:392)
        at org.gjt.xpp.sax2.Driver.parseSubTree(Driver.java:415)
        at org.gjt.xpp.sax2.Driver.parse(Driver.java:310)
```

**Comment by KengoTODA** [comment]
`spring-boot-gradle-plugin` does not have version 4.5.1, I assume your build script itself has some problem.
I created [a MCVE project based on this issue](https://github.com/KengoTODA/mcve-for-spotbugs-gradle-plugin-370) but [the build failure could not be reproduced](https://github.com/KengoTODA/mcve-for-spotbugs-gradle-plugin-370/runs/1329558478).

Hint: This is a known bug of dom4j v2.1.3: https://github.com/dom4j/dom4j/issues/85 So your classpath probably contains dom4j v2.1.3 without excluding needless dependencies. Hope that [our solution](https://github.com/spotbugs/spotbugs/pull/1131/files#diff-fe513261a5782e3b7cae4d96f221c4ed41a9a075a5b43625596be668fe3fa188R66-R76) can be a good reference for you.

**Comment by jscancella** [comment]
@saradach please reopen if you have more information to add
