### ISSUE TITLE
Spotbugs task fails with Gradle 5.0 nightly and reports enabled.

### ISSUE THREAD

**Issue by chali** [spotbugs/spotbugs-gradle-plugin#52]
Hello @KengoTODA 

I have a project where I configure SpotBugsTask tasks to print out html and xml reports
```
tasks.withType(SpotBugsTask) { task ->
  task.reports { r ->
    r.xml.enabled = true
    r.html.enabled = true
  }
}
```

When I'm using latest Gradle 5.0 nightly build fails.
I'm running `./gradlew build --stacktrace`

An interesting part of the stacktrace is:
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/ClosureBackedAction
        at com.github.spotbugs.SpotBugsTask.reports(SpotBugsTask.java:136)
        at com.github.spotbugs.SpotBugsTask.reports(SpotBugsTask.java:55)
        at org.gradle.api.reporting.Reporting$reports.call(Unknown Source)
        at build_9sk7crqolfjf8m0yenkwy63v1$_run_closure1.doCall(/Users/mchalupa/projects/others/spotbugsFailExample/build.gradle:18)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:130)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:600)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:92)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:103)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:161)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:190)
        at org.gradle.api.internal.tasks.DefaultRealizableTaskCollection.all(DefaultRealizableTaskCollection.java:229)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:201)
        at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
        at build_9sk7crqolfjf8m0yenkwy63v1.run(/Users/mchalupa/projects/others/spotbugsFailExample/build.gradle:17)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 102 more
```

The class was actually relocated. The fix depends on how you would like to maintain backward compatibility. My guess is that simple change of import could be the fix but that would mean breaking compatibility with Gradle <5.0

What are your thoughts? Gradle 5.0 is planned in the second half of October.

Here is a complete sample project: https://github.com/chali/spotbugsFailExample/tree/Gradle50

**Comment by KengoTODA** [comment]
maybe related with #51

**Comment by chali** [comment]
Awesome! And it even solves the problem with backward compatibility. Do you plan to do a patch release so we can further test it with following Gradle 5.0 Nightly builds?

**Comment by KengoTODA** [comment]
@chali version 1.6.4 has been released, please use this.

https://plugins.gradle.org/plugin/com.github.spotbugs
